APP-5895: [Android] Cannot upload Georgian identity document via the app
paysera/java-lib-wallet-sdk pull request #116
Opened 2023-06-22 05:10 UTC by gilbertparreno

2023-06-22 05:41 UTC, AndriiSerheniuk commented on wallet/src/main/java/com/paysera/lib/wallet/clients/BaseAsyncClient.java
> +            if (jsonObject.optJSONArray(code) != null) {
jsonObject.getJSONArray(code) is used twice. Can be reduced by assigning to variable

2023-06-22 06:58 UTC, gilbertparreno commented on wallet/src/main/java/com/paysera/lib/wallet/clients/BaseAsyncClient.java
> +            if (jsonObject.optJSONArray(code) != null) {
I've adjusted the code by ignoring non json array in error_properties

2023-06-27 07:00 UTC, AndriiSerheniuk approved these changes

2023-06-30 05:38 UTC, eunicegalang requested changes

2023-06-30 05:38 UTC, eunicegalang commented on buildSrc/src/main/kotlin/ApplicationConfiguration.kt
> +    const val version = "6.8.27-SNAPSHOT"
SNAPSHOT can be removed

2023-07-03 05:48 UTC, eunicegalang approved these changes

2023-07-03 05:50 UTC, merged