APP-2089: add new constants for recurrence notification
paysera/java-lib-wallet-sdk pull request #93
Opened 2021-11-03 09:42 UTC by railianmaksym

2021-11-03 11:07 UTC, gilbertparreno commented
create helper methods too for recurrence object events.

2021-11-03 11:52 UTC, eunicegalang commented
Upgrade `version` from ApplicationConfiguration

2021-11-03 11:56 UTC, eunicegalang requested changes

2021-11-03 11:56 UTC, eunicegalang commented on wallet/src/main/java/com/paysera/lib/wallet/entities/notification/NotificationSubscriber.java
> +                    event.eventName.equals(NotificationEvent.EVENT_NAME_FAILED)
fix spacing indentation

2021-11-03 11:56 UTC, eunicegalang commented on wallet/src/main/java/com/paysera/lib/wallet/entities/notification/NotificationSubscriber.java
> +                    event.eventName.equals(NotificationEvent.EVENT_NAME_DONE)
here too

2021-11-03 12:32 UTC, railianmaksym commented on wallet/src/main/java/com/paysera/lib/wallet/entities/notification/NotificationSubscriber.java
> +                    event.eventName.equals(NotificationEvent.EVENT_NAME_FAILED)
✅

2021-11-03 12:32 UTC, railianmaksym commented on wallet/src/main/java/com/paysera/lib/wallet/entities/notification/NotificationSubscriber.java
> +                    event.eventName.equals(NotificationEvent.EVENT_NAME_DONE)
✅

2021-11-04 01:30 UTC, gilbertparreno commented
everything else is okay with me :)

2021-11-04 03:07 UTC, merged